apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-green
  namespace: expense
  # labels of deployment resource
  labels:
    app: backend
    tier: backend
    project: expense
    version: green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
      tier: backend
      project: expense
      version: green
  template:
    metadata:
      labels:
        app: backend
        tier: backend
        project: expense
        version: green
    spec:
      containers:
      - name: backend
        image: arun596/green:2.0.0
        resources:
          requests: #soft limit
            memory: "512Mi"
            cpu: "500m"
          limits: # hard limit 
            memory: "1Gi"
            cpu: "1"
        envFrom:
        - configMapRef:
            name: backend
